IDF_EXPORT := /Users/alex/esp-idf-v6.0.1/export.sh
PORT       := /dev/cu.usbmodem101
IDF        := . $(IDF_EXPORT) >/dev/null && idf.py
KERNEL_SRC := ../monoblok/lib/patchbay/src/kernel.zig
KERNEL_DST := main/zig/kernel.zig
KERNEL_REMOTE_REF := main
KERNEL_REMOTE_URL := https://raw.githubusercontent.com/lexvicacom/monoblok/$(KERNEL_REMOTE_REF)/lib/patchbay/src/kernel.zig

.PHONY: gen soundcheck build test flash monitor flash-monitor clean fullclean menuconfig sync-kernel sync-kernel-remote

# rules.zig is regenerated by CMake during `idf.py build` whenever patchbay.edn
# or gen.py changes (see main/CMakeLists.txt). This target is a manual escape
# hatch for regenerating without touching the build tree.
gen:
	@echo "GEN patchbay.edn -> main/zig/rules.zig"
	@python3 tools/gen.py patchbay.edn main/zig/rules.zig

soundcheck: gen
	@echo "ZIG ./soundcheck"
	@ZIG_GLOBAL_CACHE_DIR=.zig-cache zig build soundcheck --prefix .

# Re-vendor the patchbay op kernel from monoblok. Source of truth lives there;
# tinyblok carries a byte-identical copy so codegen can target the same APIs.
sync-kernel:
	@if [ ! -f "$(KERNEL_SRC)" ]; then \
		echo "error: $(KERNEL_SRC) not found (is monoblok checked out next to tinyblok?)" >&2; exit 1; \
	fi
	@if cmp -s "$(KERNEL_SRC)" "$(KERNEL_DST)"; then \
		echo "kernel.zig already in sync"; \
	else \
		cp "$(KERNEL_SRC)" "$(KERNEL_DST)" && echo "updated $(KERNEL_DST) from $(KERNEL_SRC)"; \
	fi

# Re-vendor from GitHub instead of a sibling checkout. Override
# KERNEL_REMOTE_REF=branch-or-sha to pin a specific upstream revision.
sync-kernel-remote:
	@tmp=$$(mktemp); \
	trap 'rm -f "$$tmp"' EXIT; \
	curl -fsSL "$(KERNEL_REMOTE_URL)" -o "$$tmp"; \
	if cmp -s "$$tmp" "$(KERNEL_DST)"; then \
		echo "kernel.zig already in sync with $(KERNEL_REMOTE_URL)"; \
	else \
		cp "$$tmp" "$(KERNEL_DST)" && echo "updated $(KERNEL_DST) from $(KERNEL_REMOTE_URL)"; \
	fi

build:
	@$(IDF) build

# Host-side unit tests. Runs `zig test` against modules that don't depend on
# firmware-only externs (FreeRTOS, lwIP, ESP drivers). Today that's just the
# vendored kernel; add new entries here as more modules become host-portable.
test:
	@zig test main/zig/kernel.zig

flash: build
	@$(IDF) -p $(PORT) flash

monitor:
	@echo "(exit with Ctrl+])"
	@$(IDF) -p $(PORT) monitor

flash-monitor: build
	@echo "(exit with Ctrl+])"
	@$(IDF) -p $(PORT) flash monitor

clean:
	@$(IDF) clean

fullclean:
	@$(IDF) fullclean

menuconfig:
	@$(IDF) menuconfig
