IDF_EXPORT := /Users/alex/esp-idf-v6.0.1/export.sh
PORT       := /dev/cu.usbmodem101
IDF        := . $(IDF_EXPORT) >/dev/null && idf.py
KERNEL_SRC := ../monoblok/lib/patchbay/src/kernel.zig
KERNEL_DST := main/kernel.zig

.PHONY: gen build flash monitor flash-monitor clean fullclean menuconfig sync-kernel

# rules.zig is regenerated by CMake during `idf.py build` whenever patchbay.edn
# or gen.py changes (see main/CMakeLists.txt). This target is a manual escape
# hatch for regenerating without touching the build tree.
gen:
	@python3 tools/gen.py patchbay.edn main/rules.zig

# Re-vendor the patchbay op kernel from monoblok. Source of truth lives there;
# tinyblok carries a byte-identical copy so codegen can target the same APIs.
sync-kernel:
	@if [ ! -f "$(KERNEL_SRC)" ]; then \
		echo "error: $(KERNEL_SRC) not found (is monoblok checked out next to tinyblok?)" >&2; exit 1; \
	fi
	@if cmp -s "$(KERNEL_SRC)" "$(KERNEL_DST)"; then \
		echo "kernel.zig already in sync"; \
	else \
		cp "$(KERNEL_SRC)" "$(KERNEL_DST)" && echo "updated $(KERNEL_DST) from $(KERNEL_SRC)"; \
	fi

build:
	@$(IDF) build

flash: build
	@$(IDF) -p $(PORT) flash

monitor:
	@echo "(exit with Ctrl+])"
	@$(IDF) -p $(PORT) monitor

flash-monitor: build
	@echo "(exit with Ctrl+])"
	@$(IDF) -p $(PORT) flash monitor

clean:
	@$(IDF) clean

fullclean:
	@$(IDF) fullclean

menuconfig:
	@$(IDF) menuconfig
