IDF_EXPORT     ?=
IDF_PATH       ?=
DEFAULT_IDF_PATH ?= $(HOME)/esp-idf-v6.0.1
IDF_PY         ?= idf.py
PORT           ?=
KERNEL_SRC     ?= ../monoblok/lib/patchbay/src/kernel.zig
KERNEL_DST     ?= main/zig/kernel.zig
KERNEL_REMOTE_REF ?= main
KERNEL_REMOTE_URL ?= https://raw.githubusercontent.com/lexvicacom/monoblok/$(KERNEL_REMOTE_REF)/lib/patchbay/src/kernel.zig
HOST_CC        ?= zig cc
NATS_HOST_PORT ?= 4223
HOST_BUILD_DIR ?= build/host

-include local.mk

ifeq ($(strip $(IDF_PATH)),)
ifneq ($(wildcard $(DEFAULT_IDF_PATH)/export.sh),)
IDF_PATH := $(DEFAULT_IDF_PATH)
endif
endif

ifeq ($(strip $(IDF_EXPORT)),)
ifneq ($(strip $(IDF_PATH)),)
IDF_EXPORT := $(IDF_PATH)/export.sh
endif
endif

ifneq ($(strip $(IDF_EXPORT)),)
IDF := . "$(IDF_EXPORT)" >/dev/null && $(IDF_PY)
else
IDF := $(IDF_PY)
endif

PORT_ARG := $(if $(strip $(PORT)),-p $(PORT),)

.PHONY: check-idf gen soundcheck build test nats-host-smoke flash monitor flash-monitor clean fullclean menuconfig sync-kernel sync-kernel-remote

check-idf:
	@if [ -n "$(IDF_EXPORT)" ]; then \
		if [ ! -f "$(IDF_EXPORT)" ]; then \
			echo "error: IDF export script not found: $(IDF_EXPORT)" >&2; \
			echo "hint: set IDF_PATH=/path/to/esp-idf or IDF_EXPORT=/path/to/esp-idf/export.sh" >&2; \
			exit 1; \
		fi; \
	elif ! command -v "$(IDF_PY)" >/dev/null 2>&1; then \
		echo "error: $(IDF_PY) not found in PATH" >&2; \
		echo "hint: run '. /path/to/esp-idf/export.sh', set IDF_PATH=/path/to/esp-idf, or pass IDF_EXPORT=/path/to/esp-idf/export.sh" >&2; \
		exit 1; \
	fi

# rules.zig is regenerated by CMake during `idf.py build` whenever patchbay.edn
# or gen.py changes (see main/CMakeLists.txt). This target is a manual escape
# hatch for regenerating without touching the build tree.
gen:
	@echo "GEN patchbay.edn -> main/zig/rules.zig"
	@python3 tools/gen.py patchbay.edn main/zig/rules.zig

soundcheck: gen
	@echo "ZIG ./soundcheck"
	@ZIG_GLOBAL_CACHE_DIR=.zig-cache zig build soundcheck --prefix .

# Re-vendor the patchbay op kernel from monoblok. Source of truth lives there;
# tinyblok carries a byte-identical copy so codegen can target the same APIs.
sync-kernel:
	@if [ ! -f "$(KERNEL_SRC)" ]; then \
		echo "error: $(KERNEL_SRC) not found (is monoblok checked out next to tinyblok?)" >&2; exit 1; \
	fi
	@if cmp -s "$(KERNEL_SRC)" "$(KERNEL_DST)"; then \
		echo "kernel.zig already in sync"; \
	else \
		cp "$(KERNEL_SRC)" "$(KERNEL_DST)" && echo "updated $(KERNEL_DST) from $(KERNEL_SRC)"; \
	fi

# Re-vendor from GitHub instead of a sibling checkout. Override
# KERNEL_REMOTE_REF=branch-or-sha to pin a specific upstream revision.
sync-kernel-remote:
	@tmp=$$(mktemp); \
	trap 'rm -f "$$tmp"' EXIT; \
	curl -fsSL "$(KERNEL_REMOTE_URL)" -o "$$tmp"; \
	if cmp -s "$$tmp" "$(KERNEL_DST)"; then \
		echo "kernel.zig already in sync with $(KERNEL_REMOTE_URL)"; \
	else \
		cp "$$tmp" "$(KERNEL_DST)" && echo "updated $(KERNEL_DST) from $(KERNEL_REMOTE_URL)"; \
	fi

build: check-idf
	@$(IDF) build

# Host-side unit tests. Runs `zig test` against modules that don't depend on
# firmware-only externs (FreeRTOS, lwIP, ESP drivers). Today that's just the
# vendored kernel; add new entries here as more modules become host-portable.
test: gen
	@zig test main/zig/kernel.zig
	@ZIG_GLOBAL_CACHE_DIR=.zig-cache zig build soundcheck-test

nats-host-smoke:
	@command -v nats-server >/dev/null || { echo "error: nats-server not found in PATH" >&2; exit 1; }
	@command -v nats >/dev/null || { echo "error: nats CLI not found in PATH" >&2; exit 1; }
	@mkdir -p $(HOST_BUILD_DIR)
	@echo "CC $(HOST_BUILD_DIR)/nats_smoke"
	@$(HOST_CC) -std=c11 -D_GNU_SOURCE -DCONFIG_TINYBLOK_NATS_PORT=$(NATS_HOST_PORT) \
		-Itests/host/include tests/host/nats_smoke.c main/c/nats.c \
		-o $(HOST_BUILD_DIR)/nats_smoke
	@echo "NATS host smoke on 127.0.0.1:$(NATS_HOST_PORT)"
	@log="$(HOST_BUILD_DIR)/nats-server.log"; \
	svc_log="$(HOST_BUILD_DIR)/nats-smoke.log"; \
	sub_log="$(HOST_BUILD_DIR)/nats-sub.log"; \
	nats-server -p $(NATS_HOST_PORT) -a 127.0.0.1 >"$$log" 2>&1 & \
	server_pid=$$!; \
	trap 'kill $$server_pid $$svc_pid $$sub_pid >/dev/null 2>&1 || true; wait $$server_pid $$svc_pid $$sub_pid >/dev/null 2>&1 || true' EXIT; \
	sleep 0.2; \
	$(HOST_BUILD_DIR)/nats_smoke serve >"$$svc_log" 2>&1 & \
	svc_pid=$$!; \
	sleep 0.2; \
	reply=$$(nats --no-context -s nats://127.0.0.1:$(NATS_HOST_PORT) request --raw --timeout 2s tinyblok.req.ping ""); \
	test "$$reply" = "pong" || { echo "unexpected nats reply: '$$reply'" >&2; cat "$$svc_log" >&2; exit 1; }; \
	for i in 1 2 3 4 5 6 7 8 9 10; do \
		if ! kill -0 $$svc_pid >/dev/null 2>&1; then \
			wait $$svc_pid; \
			cat "$$svc_log"; \
			break; \
		fi; \
		sleep 0.1; \
	done; \
	if kill -0 $$svc_pid >/dev/null 2>&1; then \
		echo "nats smoke service did not exit after reply" >&2; \
		cat "$$svc_log" >&2; \
		echo "nats host smoke failed; server log:" >&2; \
		tail -40 "$$log" >&2; \
		exit 1; \
	fi; \
	nats --no-context -s nats://127.0.0.1:$(NATS_HOST_PORT) subscribe --raw --count 5 --wait 2s tinyblok.host.pub >"$$sub_log" 2>&1 & \
	sub_pid=$$!; \
	sleep 0.2; \
	$(HOST_BUILD_DIR)/nats_smoke pub; \
	wait $$sub_pid; \
	pub=$$(cat "$$sub_log"); \
	expected=$$(printf "beep0\nbeep1\nbeep2\nbeep3\nbeep4"); \
	test "$$pub" = "$$expected" || { echo "unexpected pub payloads:" >&2; cat "$$sub_log" >&2; exit 1; }; \
	echo "ok nats cli observed pub batch"; \
	cat "$$sub_log"

flash: build
	@$(IDF) $(PORT_ARG) flash

monitor: check-idf
	@echo "(exit with Ctrl+])"
	@$(IDF) $(PORT_ARG) monitor

flash-monitor: build
	@echo "(exit with Ctrl+])"
	@$(IDF) $(PORT_ARG) flash monitor

clean: check-idf
	@$(IDF) clean

fullclean: check-idf
	@$(IDF) fullclean

menuconfig: check-idf
	@$(IDF) menuconfig
