// Each generated pump arms one esp_timer that posts to TINYBLOK_EVENTS.
// on_pump_event runs on the esp_event task and calls into the Zig-side
// pump table; the main loop only services network I/O.
//
// A second esp_timer drives the time-bar walker (tinyblok_bar_tick_clocks),
// generated by tools/gen.py. It closes wall-clock OHLC windows that elapsed
// without a new sample landing past the boundary. Quiet feeds still flush
// their bars on time.

#include <stdint.h>
#include <stddef.h>

#include "esp_event.h"
#include "esp_log.h"
#include "esp_timer.h"

ESP_EVENT_DEFINE_BASE(TINYBLOK_EVENTS);

#define TINYBLOK_BAR_WALK_ID 0x7FFFFFFE
#define TINYBLOK_BAR_WALK_PERIOD_US 500000ULL

static const char *TAG = "drivers";

typedef struct
{
    const char *subject;
    uint64_t period_us;
    void (*fire)(void);
} tinyblok_pump_t;

extern const size_t tinyblok_pump_count;
extern const tinyblok_pump_t tinyblok_pumps[];
extern void tinyblok_bar_tick_clocks(void);

int64_t tinyblok_now_ms(void)
{
    return esp_timer_get_time() / 1000;
}

static void on_pump_event(void *arg, esp_event_base_t base, int32_t id, void *data)
{
    (void)arg;
    (void)base;
    (void)data;
    if (id == TINYBLOK_BAR_WALK_ID) {
        tinyblok_bar_tick_clocks();
        return;
    }
    if ((size_t)id >= tinyblok_pump_count)
        return;
    tinyblok_pumps[id].fire();
}

static void timer_cb(void *arg)
{
    intptr_t id = (intptr_t)arg;
    esp_event_post(TINYBLOK_EVENTS, (int32_t)id, NULL, 0, 0);
}

void tinyblok_drivers_start(void)
{
    ESP_ERROR_CHECK(esp_event_handler_register(TINYBLOK_EVENTS, ESP_EVENT_ANY_ID,
                                               &on_pump_event, NULL));

    for (size_t i = 0; i < tinyblok_pump_count; i++)
    {
        const tinyblok_pump_t *p = &tinyblok_pumps[i];
        esp_timer_handle_t t;
        const esp_timer_create_args_t args = {
            .callback = &timer_cb,
            .arg = (void *)(intptr_t)i,
            .dispatch_method = ESP_TIMER_TASK,
            .name = p->subject,
        };
        ESP_ERROR_CHECK(esp_timer_create(&args, &t));
        ESP_ERROR_CHECK(esp_timer_start_periodic(t, p->period_us));
        ESP_LOGI(TAG, "pump '%s' armed @ %llu us", p->subject,
                 (unsigned long long)p->period_us);
    }

    esp_timer_handle_t bar_walker;
    const esp_timer_create_args_t bar_args = {
        .callback = &timer_cb,
        .arg = (void *)(intptr_t)TINYBLOK_BAR_WALK_ID,
        .dispatch_method = ESP_TIMER_TASK,
        .name = "bar-walker",
    };
    ESP_ERROR_CHECK(esp_timer_create(&bar_args, &bar_walker));
    ESP_ERROR_CHECK(esp_timer_start_periodic(bar_walker, TINYBLOK_BAR_WALK_PERIOD_US));
    ESP_LOGI(TAG, "bar walker armed @ %llu us", (unsigned long long)TINYBLOK_BAR_WALK_PERIOD_US);
}
