// AUTO-GENERATED by tools/gen.py — do not edit by hand.
// Regenerate after editing patchbay.edn:
//   make gen
//
const pb = @import("patchbay.zig");

extern fn snprintf(buf: [*]u8, len: usize, fmt: [*:0]const u8, ...) c_int;
extern fn vTaskDelay(ticks: u32) void;
extern fn tinyblok_uptime_us() u64;
extern fn strtod(nptr: [*:0]const u8, endptr: ?*[*:0]const u8) f64;
extern fn tinyblok_free_heap() u32;
extern fn tinyblok_wifi_rssi() c_int;
extern fn tinyblok_read_temp_c() f32;

const State = struct {
    rule0_db0: pb.Deadband = .{ .threshold = 1024 },
    rule1_ma1: pb.MovingAvg(10) = .{},
    rule2_re2: pb.RisingEdge = .{},
    rule3_db3: pb.Deadband = .{ .threshold = 2 },
    rule4_ma4: pb.MovingAvg(50) = .{},
    rule5_re5: pb.RisingEdge = .{},
    rule6_th6: pb.Throttle = .{ .interval_us = 60000000 },
    rule7_ma7: pb.MovingAvg(30) = .{},
    rule8_re8: pb.RisingEdge = .{},
};

var state: State = .{};

fn onHeap(payload_float: f64) void {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule0_db0.update(__v0) orelse break :blk;
        pb.emitFloat("tinyblok.heap.stable", __v1, 6);
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule1_ma1.update(__v0);
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.heap.avg1s", __v2, 6);
    }
    if ((payload_float < @as(f64, 20480))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: bool = state.rule2_re2.update(__v0 != 0);
        if (!__v1) break :blk;
        pb.emit("tinyblok.alert.heap.low", "1");
    }
    }
}

fn onRssi(payload_float: f64) void {
    if (!((payload_float == @as(f64, 0)))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule3_db3.update(__v0) orelse break :blk;
        pb.emitFloat("tinyblok.rssi.stable", __v1, 6);
    }
    }
    if (!((payload_float == @as(f64, 0)))) {
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule4_ma4.update(__v0);
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.rssi.avg5s", __v2, 6);
    }
    }
    if ((!((payload_float == @as(f64, 0))) and (payload_float < @as(f64, -75)))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: bool = state.rule5_re5.update(__v0 != 0);
        if (!__v1) break :blk;
        pb.emit("tinyblok.alert.rssi.weak", "1");
    }
    }
}

fn onUptime(payload_float: f64) void {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule6_th6.update(__v0, tinyblok_uptime_us()) orelse break :blk;
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.uptime.1m", __v2, 6);
    }
}

fn onTemp(payload_float: f64) void {
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule7_ma7.update(__v0);
        const __v2: f64 = @round(__v1 * 10) / 10;
        pb.emitFloat("tinyblok.temp.avg30s", __v2, 6);
    }
    if ((payload_float > @as(f64, 30))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: bool = state.rule8_re8.update(__v0 != 0);
        if (!__v1) break :blk;
        pb.emit("tinyblok.alert.temp.hot", "1");
    }
    }
}

fn onAlex(payload_float: f64) void {
    if ((payload_float == @as(f64, 42))) {
    {
        const __v0: f64 = @as(f64, 1);
        pb.emitFloat("alex.alert", __v0, 6);
    }
    }
}

fn eql(a: []const u8, b: []const u8) bool {
    if (a.len != b.len) return false;
    var i: usize = 0;
    while (i < a.len) : (i += 1) if (a[i] != b[i]) return false;
    return true;
}

pub fn dispatch(subject: []const u8, payload: []const u8) void {
    var subj_buf: [64]u8 = undefined;
    if (subject.len + 1 > subj_buf.len) return;
    @memcpy(subj_buf[0..subject.len], subject);
    subj_buf[subject.len] = 0;
    const subj_z: [*:0]const u8 = @ptrCast(&subj_buf);

    var pl_buf: [64]u8 = undefined;
    if (payload.len + 1 > pl_buf.len) return;
    @memcpy(pl_buf[0..payload.len], payload);
    pl_buf[payload.len] = 0;
    const pl_z: [*:0]const u8 = @ptrCast(&pl_buf);

    pb.emit(subj_z, payload);
    const v: f64 = strtod(pl_z, null);

    if (eql(subject, "tinyblok.heap")) {
        onHeap(v);
    } else if (eql(subject, "tinyblok.rssi")) {
        onRssi(v);
    } else if (eql(subject, "tinyblok.uptime")) {
        onUptime(v);
    } else if (eql(subject, "tinyblok.temp")) {
        onTemp(v);
    } else if (eql(subject, "alex")) {
        onAlex(v);
    }
}

pub const tick_hz: u32 = 10;
pub const tick_ms: u32 = 100;

fn dispatchFmt(subject: []const u8, comptime fmt: [*:0]const u8, args: anytype) void {
    var buf: [32]u8 = undefined;
    const n = @call(.auto, snprintf, .{ &buf, buf.len, fmt } ++ args);
    if (n <= 0) return;
    const len: usize = @min(@as(usize, @intCast(n)), buf.len - 1);
    dispatch(subject, buf[0..len]);
}

pub fn collect() void {
    const State_ = struct { var counter: u32 = 0; };
    const c = State_.counter;
    dispatchFmt("tinyblok.heap", "%lu", .{tinyblok_free_heap()});
    dispatchFmt("tinyblok.rssi", "%d", .{tinyblok_wifi_rssi()});
    dispatchFmt("tinyblok.uptime", "%.3f", .{@as(f64, @floatFromInt(tinyblok_uptime_us())) / 1_000_000.0});
    if (c % 10 == 0) dispatchFmt("tinyblok.temp", "%.7f", .{@as(f64, tinyblok_read_temp_c())});
    State_.counter = c +% 1;
}
