// AUTO-GENERATED by tools/gen.py — do not edit by hand.
// Regenerate after editing patchbay.edn:
//   make gen
//
const pb = @import("patchbay.zig");

extern fn snprintf(buf: [*]u8, len: usize, fmt: [*:0]const u8, ...) c_int;
extern fn vTaskDelay(ticks: u32) void;
extern fn tinyblok_uptime_us() u64;
extern fn tinyblok_now_ms() i64;
extern fn strtod(nptr: [*:0]const u8, endptr: ?*[*:0]const u8) f64;
extern fn tinyblok_free_heap() u32;
extern fn tinyblok_wifi_rssi() c_int;
extern fn tinyblok_read_temp_c() f32;

const State = struct {
    rule0_db0: pb.Deadband = .{ .threshold = 1024 },
    rule1_ma1: pb.MovingAvg(10) = .{},
    rule2_re2: pb.RisingEdge = .{},
    rule3_db3: pb.Deadband = .{ .threshold = 2 },
    rule4_ma4: pb.MovingAvg(50) = .{},
    rule5_re5: pb.RisingEdge = .{},
    rule6_th6: pb.Throttle = .{ .interval_us = 60000000 },
    rule7_ma7: pb.MovingAvg(30) = .{},
    rule8_re8: pb.RisingEdge = .{},
    rule11_bk9: pb.Bar = .{ .cap = 10 },
    rule12_bt10: pb.Bar = .{ .window_ms = 60000 },
    rule13_mx11: pb.MovingMax(30) = .{},
    rule14_mn12: pb.MovingMin(30) = .{},
    rule17_ct13: pb.Count = .{},
};

var state: State = .{};

fn onHeap(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = payload_raw;
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule0_db0.update(__v0) orelse break :blk;
        pb.emitReentrantFloat("tinyblok.heap.stable", __v1, depth, &dispatchInternal);
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule1_ma1.update(__v0);
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.heap.avg1s", __v2, 6);
    }
    {
        const __v0: f64 = payload_float;
        if (state.rule12_bt10.timeUpdate(tinyblok_now_ms(), __v0)) |__c| {
            pb.emitFloat("tinyblok.heap.bar.open", __c.open, 6);
            pb.emitFloat("tinyblok.heap.bar.high", __c.high, 6);
            pb.emitFloat("tinyblok.heap.bar.low", __c.low, 6);
            pb.emitFloat("tinyblok.heap.bar.close", __c.close, 6);
        }
        if (state.rule12_bt10.nextDeadlineMs()) |__dl| {
            tinyblok_clock_arm(0, deadlineUsFromNow(__dl));
        }
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = pb.quantize(4096, __v0);
        pb.emitFloat("tinyblok.heap.bucket", __v1, 6);
    }
}

fn onHeap_stable(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    if ((payload_float < @as(f64, 20480))) {
        blk: {
            const __v0: f64 = payload_float;
            const __v1: bool = state.rule2_re2.update(__v0 != 0);
            if (!__v1) break :blk;
            pb.emit("tinyblok.alert.heap.low", "1");
        }
    }
}

fn onRssi(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    if (!((payload_float == @as(f64, 0)))) {
        blk: {
            const __v0: f64 = payload_float;
            const __v1: f64 = state.rule3_db3.update(__v0) orelse break :blk;
            pb.emitFloat("tinyblok.rssi.stable", __v1, 6);
        }
    }
    if (!((payload_float == @as(f64, 0)))) {
        {
            const __v0: f64 = payload_float;
            const __v1: f64 = state.rule4_ma4.update(__v0);
            const __v2: f64 = @round(__v1);
            pb.emitFloat("tinyblok.rssi.avg5s", __v2, 6);
        }
    }
    if ((!((payload_float == @as(f64, 0))) and (payload_float < @as(f64, -75)))) {
        blk: {
            const __v0: f64 = payload_float;
            const __v1: bool = state.rule5_re5.update(__v0 != 0);
            if (!__v1) break :blk;
            pb.emit("tinyblok.alert.rssi.weak", "1");
        }
    }
    if (!((payload_float == @as(f64, 0)))) {
        {
            const __v0: f64 = payload_float;
            const __v1: f64 = pb.clamp(-100, 0, __v0);
            pb.emitFloat("tinyblok.rssi.clamped", __v1, 6);
        }
    }
}

fn onUptime(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule6_th6.update(__v0, tinyblok_uptime_us()) orelse break :blk;
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.uptime.1m", __v2, 6);
    }
}

fn onTemp(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule7_ma7.update(__v0);
        const __v2: f64 = @round(__v1 * 10) / 10;
        pb.emitFloat("tinyblok.temp.avg30s", __v2, 6);
    }
    if ((payload_float > @as(f64, 30))) {
        blk: {
            const __v0: f64 = payload_float;
            const __v1: bool = state.rule8_re8.update(__v0 != 0);
            if (!__v1) break :blk;
            pb.emit("tinyblok.alert.temp.hot", "1");
        }
    }
    pb.emit("tinyblok.temp.raw", payload_raw);
    {
        const __v0: f64 = payload_float;
        if (state.rule11_bk9.tickUpdate(__v0)) |__c| {
            pb.emitFloat("tinyblok.temp.bar.open", __c.open, 6);
            pb.emitFloat("tinyblok.temp.bar.high", __c.high, 6);
            pb.emitFloat("tinyblok.temp.bar.low", __c.low, 6);
            pb.emitFloat("tinyblok.temp.bar.close", __c.close, 6);
        }
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule13_mx11.update(__v0);
        const __v2: f64 = @round(__v1 * 10) / 10;
        pb.emitFloat("tinyblok.temp.max30s", __v2, 6);
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule14_mn12.update(__v0);
        const __v2: f64 = @round(__v1 * 10) / 10;
        pb.emitFloat("tinyblok.temp.min30s", __v2, 6);
    }
    if (state.rule17_ct13.update(true)) |__n| {
        pb.emitInt("tinyblok.temp.count", @intCast(__n));
    }
}

fn onAlex(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    if ((payload_float == @as(f64, 42))) {
        {
            const __v0: f64 = @as(f64, 1);
            pb.emitFloat("alex.alert", __v0, 6);
        }
    }
}

fn eql(a: []const u8, b: []const u8) bool {
    if (a.len != b.len) return false;
    var i: usize = 0;
    while (i < a.len) : (i += 1) if (a[i] != b[i]) return false;
    return true;
}

pub fn dispatch(subject: []const u8, payload: []const u8) void {
    dispatchInternal(subject, payload, 0);
}

fn dispatchInternal(subject: []const u8, payload: []const u8, depth: u8) void {
    if (depth >= pb.MAX_DEPTH) return;
    var subj_buf: [64]u8 = undefined;
    if (subject.len + 1 > subj_buf.len) return;
    @memcpy(subj_buf[0..subject.len], subject);
    subj_buf[subject.len] = 0;
    const subj_z: [*:0]const u8 = @ptrCast(&subj_buf);

    var pl_buf: [64]u8 = undefined;
    if (payload.len + 1 > pl_buf.len) return;
    @memcpy(pl_buf[0..payload.len], payload);
    pl_buf[payload.len] = 0;
    const pl_z: [*:0]const u8 = @ptrCast(&pl_buf);

    // Top-level inputs are wired to NATS; re-entered subjects are
    // already on the wire via pb.emitReentrant before we recurse.
    if (depth == 0) pb.emit(subj_z, payload);
    const v: f64 = strtod(pl_z, null);

    if (eql(subject, "tinyblok.heap")) {
        onHeap(v, payload, depth);
    } else if (eql(subject, "tinyblok.heap.stable")) {
        onHeap_stable(v, payload, depth);
    } else if (eql(subject, "tinyblok.rssi")) {
        onRssi(v, payload, depth);
    } else if (eql(subject, "tinyblok.uptime")) {
        onUptime(v, payload, depth);
    } else if (eql(subject, "tinyblok.temp")) {
        onTemp(v, payload, depth);
    } else if (eql(subject, "alex")) {
        onAlex(v, payload, depth);
    }
}

fn dispatchFmt(subject: []const u8, comptime fmt: [*:0]const u8, args: anytype) void {
    var buf: [32]u8 = undefined;
    const n = @call(.auto, snprintf, .{ &buf, buf.len, fmt } ++ args);
    if (n <= 0) return;
    const len: usize = @min(@as(usize, @intCast(n)), buf.len - 1);
    dispatch(subject, buf[0..len]);
}

export fn tinyblok_pump_heap() callconv(.c) void {
    dispatchFmt("tinyblok.heap", "%lu", .{tinyblok_free_heap()});
}

export fn tinyblok_pump_rssi() callconv(.c) void {
    dispatchFmt("tinyblok.rssi", "%d", .{tinyblok_wifi_rssi()});
}

export fn tinyblok_pump_uptime() callconv(.c) void {
    dispatchFmt("tinyblok.uptime", "%.3f", .{@as(f64, @floatFromInt(tinyblok_uptime_us())) / 1_000_000.0});
}

export fn tinyblok_pump_temp() callconv(.c) void {
    dispatchFmt("tinyblok.temp", "%.7f", .{@as(f64, tinyblok_read_temp_c())});
}

pub const Pump = extern struct {
    subject: [*:0]const u8,
    period_us: u64,
    fire: *const fn () callconv(.c) void,
};

export const tinyblok_pump_count: usize = 4;
export const tinyblok_pumps: [4]Pump = .{
    .{ .subject = "tinyblok.heap", .period_us = 100000, .fire = &tinyblok_pump_heap },
    .{ .subject = "tinyblok.rssi", .period_us = 100000, .fire = &tinyblok_pump_rssi },
    .{ .subject = "tinyblok.uptime", .period_us = 100000, .fire = &tinyblok_pump_uptime },
    .{ .subject = "tinyblok.temp", .period_us = 1000000, .fire = &tinyblok_pump_temp },
};

extern fn tinyblok_clock_arm(slot_id: usize, us_until: u64) void;

fn deadlineUsFromNow(deadline_ms: i64) u64 {
    const now_ms = tinyblok_now_ms();
    const diff = deadline_ms - now_ms;
    if (diff <= 0) return 0;
    return @as(u64, @intCast(diff)) * 1000;
}

export fn tinyblok_bar_rule12_bt10_fire() callconv(.c) void {
    const now_ms: i64 = tinyblok_now_ms();
    if (state.rule12_bt10.timeTick(now_ms)) |__c| {
        pb.emitFloat("tinyblok.heap.bar.open", __c.open, 6);
        pb.emitFloat("tinyblok.heap.bar.high", __c.high, 6);
        pb.emitFloat("tinyblok.heap.bar.low", __c.low, 6);
        pb.emitFloat("tinyblok.heap.bar.close", __c.close, 6);
    }
    if (state.rule12_bt10.nextDeadlineMs()) |__dl| {
        tinyblok_clock_arm(0, deadlineUsFromNow(__dl));
    }
}

pub const ClockSlot = extern struct {
    fire: *const fn () callconv(.c) void,
};

export const tinyblok_clock_slot_count: usize = 1;
export const tinyblok_clock_slots: [1]ClockSlot = .{
    .{ .fire = &tinyblok_bar_rule12_bt10_fire },
};
