#pragma once

#ifndef CONFIG_TINYBLOK_NATS_HOST
#define CONFIG_TINYBLOK_NATS_HOST "127.0.0.1"
#endif

#ifndef CONFIG_TINYBLOK_NATS_PORT
#define CONFIG_TINYBLOK_NATS_PORT 4223
#endif

#ifndef CONFIG_TINYBLOK_NATS_CLIENT_NAME
#define CONFIG_TINYBLOK_NATS_CLIENT_NAME "tinyblok-host-smoke"
#endif

#define CONFIG_TINYBLOK_NATS_TLS 0
#define CONFIG_TINYBLOK_NATS_TLS_BUNDLE 0
#define CONFIG_TINYBLOK_NATS_CREDS_SUPPORT 0
