// AUTO-GENERATED by tools/gen.py — do not edit by hand.
// Regenerate after editing patchbay.edn:
//   make gen
//
const pb = @import("patchbay.zig");

extern fn snprintf(buf: [*]u8, len: usize, fmt: [*:0]const u8, ...) c_int;
extern fn vTaskDelay(ticks: u32) void;
extern fn tinyblok_uptime_us() u64;
extern fn tinyblok_now_ms() i64;
extern fn strtod(nptr: [*:0]const u8, endptr: ?*[*:0]const u8) f64;
extern fn tinyblok_free_heap() u32;
extern fn tinyblok_wifi_rssi() c_int;
extern fn tinyblok_read_temp_c() f32;

const State = struct {
    rule0_db0: pb.Deadband = .{ .threshold = 1024 },
    rule1_ma1: pb.MovingAvg(10) = .{},
    rule2_re2: pb.RisingEdge = .{},
    rule3_db3: pb.Deadband = .{ .threshold = 2 },
    rule4_ma4: pb.MovingAvg(50) = .{},
    rule5_sa5: pb.ClockEmitter = .{ .period_ms = 5000 },
    rule6_dbn6: pb.ClockEmitter = .{ .period_ms = 1000 },
    rule7_re7: pb.RisingEdge = .{},
    rule8_th8: pb.Throttle = .{ .interval_us = 60000000 },
    rule9_ma9: pb.MovingAvg(30) = .{},
    rule10_re10: pb.RisingEdge = .{},
    rule13_bk11: pb.Bar = .{ .cap = 10 },
    rule14_bt12: pb.Bar = .{ .window_ms = 60000 },
    rule15_mx13: pb.MovingMax(30) = .{},
    rule16_mn14: pb.MovingMin(30) = .{},
    rule19_ct15: pb.Count = .{},
};

var state: State = .{};

fn onHeap(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = payload_raw;
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule0_db0.update(__v0) orelse break :blk;
        pb.emitReentrantFloat("tinyblok.heap.stable", __v1, depth, &dispatchInternal);
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule1_ma1.update(__v0);
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.heap.avg1s", __v2, 6);
    }
    {
        const __v0: f64 = payload_float;
        if (state.rule14_bt12.timeUpdate(tinyblok_now_ms(), __v0)) |__c| {
            pb.emitFloat("tinyblok.heap.bar.open", __c.open, 6);
            pb.emitFloat("tinyblok.heap.bar.high", __c.high, 6);
            pb.emitFloat("tinyblok.heap.bar.low", __c.low, 6);
            pb.emitFloat("tinyblok.heap.bar.close", __c.close, 6);
        }
        if (state.rule14_bt12.nextDeadlineMs()) |__dl| {
            tinyblok_clock_arm(2, deadlineUsFromNow(__dl));
        }
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = pb.quantize(4096, __v0);
        pb.emitFloat("tinyblok.heap.bucket", __v1, 6);
    }
}

fn onHeap_stable(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    if ((payload_float < @as(f64, 20480))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: bool = state.rule2_re2.update(__v0 != 0);
        if (!__v1) break :blk;
        pb.emit("tinyblok.alert.heap.low", "1");
    }
    }
}

fn onRssi(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    if (!((payload_float == @as(f64, 0)))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule3_db3.update(__v0) orelse break :blk;
        pb.emitFloat("tinyblok.rssi.stable", __v1, 6);
    }
    }
    if (!((payload_float == @as(f64, 0)))) {
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule4_ma4.update(__v0);
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.rssi.avg5s", __v2, 6);
    }
    }
    if (!((payload_float == @as(f64, 0)))) {
    {
        const __v0: f64 = payload_float;
        if (state.rule5_sa5.updateSampleFloat(tinyblok_now_ms(), __v0)) |__dl| {
            tinyblok_clock_arm(0, deadlineUsFromNow(__dl));
        }
    }
    }
    if (!((payload_float == @as(f64, 0)))) {
    {
        const __v0: f64 = payload_float;
        if (state.rule6_dbn6.updateDebounceFloat(tinyblok_now_ms(), __v0)) |__dl| {
            tinyblok_clock_arm(1, deadlineUsFromNow(__dl));
        }
    }
    }
    if ((!((payload_float == @as(f64, 0))) and (payload_float < @as(f64, -75)))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: bool = state.rule7_re7.update(__v0 != 0);
        if (!__v1) break :blk;
        pb.emit("tinyblok.alert.rssi.weak", "1");
    }
    }
    if (!((payload_float == @as(f64, 0)))) {
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = pb.clamp(-100, 0, __v0);
        pb.emitFloat("tinyblok.rssi.clamped", __v1, 6);
    }
    }
}

fn onUptime(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    blk: {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule8_th8.update(__v0, tinyblok_uptime_us()) orelse break :blk;
        const __v2: f64 = @round(__v1);
        pb.emitFloat("tinyblok.uptime.1m", __v2, 6);
    }
}

fn onTemp(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule9_ma9.update(__v0);
        const __v2: f64 = @round(__v1 * 10) / 10;
        pb.emitFloat("tinyblok.temp.avg30s", __v2, 6);
    }
    if ((payload_float > @as(f64, 30))) {
    blk: {
        const __v0: f64 = payload_float;
        const __v1: bool = state.rule10_re10.update(__v0 != 0);
        if (!__v1) break :blk;
        pb.emit("tinyblok.alert.temp.hot", "1");
    }
    }
        pb.emit("tinyblok.temp.raw", payload_raw);
    {
        const __v0: f64 = payload_float;
        if (state.rule13_bk11.tickUpdate(__v0)) |__c| {
            pb.emitFloat("tinyblok.temp.bar.open", __c.open, 6);
            pb.emitFloat("tinyblok.temp.bar.high", __c.high, 6);
            pb.emitFloat("tinyblok.temp.bar.low", __c.low, 6);
            pb.emitFloat("tinyblok.temp.bar.close", __c.close, 6);
        }
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule15_mx13.update(__v0);
        const __v2: f64 = @round(__v1 * 10) / 10;
        pb.emitFloat("tinyblok.temp.max30s", __v2, 6);
    }
    {
        const __v0: f64 = payload_float;
        const __v1: f64 = state.rule16_mn14.update(__v0);
        const __v2: f64 = @round(__v1 * 10) / 10;
        pb.emitFloat("tinyblok.temp.min30s", __v2, 6);
    }
        if (state.rule19_ct15.update(true)) |__n| {
            pb.emitInt("tinyblok.temp.count", @intCast(__n));
        }
}

fn onAlex(payload_float: f64, payload_raw: []const u8, depth: u8) void {
    _ = depth;
    _ = payload_raw;
    if ((payload_float == @as(f64, 42))) {
    {
        const __v0: f64 = @as(f64, 1);
        pb.emitFloat("alex.alert", __v0, 6);
    }
    }
}

fn reqPing(payload_float: f64, payload_raw: []const u8, reply_subject: []const u8) void {
    _ = payload_float;
    _ = payload_raw;
        pb.reply(reply_subject, "pong");
}

fn reqUptime(payload_float: f64, payload_raw: []const u8, reply_subject: []const u8) void {
    _ = payload_float;
    _ = payload_raw;
    {
        const __v0: f64 = @as(f64, @floatFromInt(tinyblok_uptime_us())) / 1_000_000.0;
        pb.replyFloat(reply_subject, __v0, 6);
    }
}

fn eql(a: []const u8, b: []const u8) bool {
    if (a.len != b.len) return false;
    var i: usize = 0;
    while (i < a.len) : (i += 1) if (a[i] != b[i]) return false;
    return true;
}

pub fn dispatch(subject: []const u8, payload: []const u8) void {
    dispatchInternal(subject, payload, 0);
}

fn dispatchInternal(subject: []const u8, payload: []const u8, depth: u8) void {
    if (depth >= pb.MAX_DEPTH) return;
    var subj_buf: [64]u8 = undefined;
    if (subject.len + 1 > subj_buf.len) return;
    @memcpy(subj_buf[0..subject.len], subject);
    subj_buf[subject.len] = 0;
    const subj_z: [*:0]const u8 = @ptrCast(&subj_buf);

    var pl_buf: [64]u8 = undefined;
    if (payload.len + 1 > pl_buf.len) return;
    @memcpy(pl_buf[0..payload.len], payload);
    pl_buf[payload.len] = 0;
    const pl_z: [*:0]const u8 = @ptrCast(&pl_buf);

    // Top-level inputs are wired to NATS; re-entered subjects are
    // already on the wire via pb.emitReentrant before we recurse.
    if (depth == 0) pb.emit(subj_z, payload);
    const v: f64 = strtod(pl_z, null);

    if (eql(subject, "tinyblok.heap")) {
        onHeap(v, payload, depth);
    } else if (eql(subject, "tinyblok.heap.stable")) {
        onHeap_stable(v, payload, depth);
    } else if (eql(subject, "tinyblok.rssi")) {
        onRssi(v, payload, depth);
    } else if (eql(subject, "tinyblok.uptime")) {
        onUptime(v, payload, depth);
    } else if (eql(subject, "tinyblok.temp")) {
        onTemp(v, payload, depth);
    } else if (eql(subject, "alex")) {
        onAlex(v, payload, depth);
    }
}

export fn tinyblok_nats_handle_msg(
    subject_ptr: [*]const u8,
    subject_len: usize,
    reply_ptr: [*]const u8,
    reply_len: usize,
    payload_ptr: [*]const u8,
    payload_len: usize,
) callconv(.c) void {
    if (payload_len + 1 > 64) return;
    const subject = subject_ptr[0..subject_len];
    const reply_subject = reply_ptr[0..reply_len];
    const payload = payload_ptr[0..payload_len];

    var pl_buf: [64]u8 = undefined;
    @memcpy(pl_buf[0..payload.len], payload);
    pl_buf[payload.len] = 0;
    const pl_z: [*:0]const u8 = @ptrCast(&pl_buf);
    const v: f64 = strtod(pl_z, null);

    if (eql(subject, "tinyblok.req.ping")) {
        reqPing(v, payload, reply_subject);
    } else if (eql(subject, "tinyblok.req.uptime")) {
        reqUptime(v, payload, reply_subject);
    }
}

pub const RequestSub = extern struct {
    subject: [*:0]const u8,
};

export const tinyblok_request_sub_count: usize = 2;
export const tinyblok_request_subs: [2]RequestSub = .{
    .{ .subject = "tinyblok.req.ping" },
    .{ .subject = "tinyblok.req.uptime" },
};

fn dispatchFmt(subject: []const u8, comptime fmt: [*:0]const u8, args: anytype) void {
    var buf: [32]u8 = undefined;
    const n = @call(.auto, snprintf, .{ &buf, buf.len, fmt } ++ args);
    if (n <= 0) return;
    const len: usize = @min(@as(usize, @intCast(n)), buf.len - 1);
    dispatch(subject, buf[0..len]);
}

export fn tinyblok_pump_heap() callconv(.c) void {
    dispatchFmt("tinyblok.heap", "%lu", .{tinyblok_free_heap()});
}

export fn tinyblok_pump_rssi() callconv(.c) void {
    dispatchFmt("tinyblok.rssi", "%d", .{tinyblok_wifi_rssi()});
}

export fn tinyblok_pump_uptime() callconv(.c) void {
    dispatchFmt("tinyblok.uptime", "%.3f", .{@as(f64, @floatFromInt(tinyblok_uptime_us())) / 1_000_000.0});
}

export fn tinyblok_pump_temp() callconv(.c) void {
    dispatchFmt("tinyblok.temp", "%.7f", .{@as(f64, tinyblok_read_temp_c())});
}

pub const Pump = extern struct {
    subject: [*:0]const u8,
    period_us: u64,
    fire: *const fn () callconv(.c) void,
};

export const tinyblok_pump_count: usize = 4;
export const tinyblok_pumps: [4]Pump = .{
    .{ .subject = "tinyblok.heap", .period_us = 100000, .fire = &tinyblok_pump_heap },
    .{ .subject = "tinyblok.rssi", .period_us = 100000, .fire = &tinyblok_pump_rssi },
    .{ .subject = "tinyblok.uptime", .period_us = 100000, .fire = &tinyblok_pump_uptime },
    .{ .subject = "tinyblok.temp", .period_us = 1000000, .fire = &tinyblok_pump_temp },
};

extern fn tinyblok_clock_arm(slot_id: usize, us_until: u64) void;

fn deadlineUsFromNow(deadline_ms: i64) u64 {
    const now_ms = tinyblok_now_ms();
    const diff = deadline_ms - now_ms;
    if (diff <= 0) return 0;
    return @as(u64, @intCast(diff)) * 1000;
}

export fn tinyblok_clock_rule5_sa5_fire() callconv(.c) void {
    const now_ms: i64 = tinyblok_now_ms();
    if (state.rule5_sa5.fireSample(now_ms)) {
        pb.emit("tinyblok.rssi.sample5s", state.rule5_sa5.payloadSlice());
    }
    if (state.rule5_sa5.nextDeadlineMs()) |__dl| {
        tinyblok_clock_arm(0, deadlineUsFromNow(__dl));
    }
}

export fn tinyblok_clock_rule6_dbn6_fire() callconv(.c) void {
    const now_ms: i64 = tinyblok_now_ms();
    if (state.rule6_dbn6.fireDebounce(now_ms)) {
        pb.emit("tinyblok.rssi.settled", state.rule6_dbn6.payloadSlice());
    }
    if (state.rule6_dbn6.nextDeadlineMs()) |__dl| {
        tinyblok_clock_arm(1, deadlineUsFromNow(__dl));
    }
}

export fn tinyblok_clock_rule14_bt12_fire() callconv(.c) void {
    const now_ms: i64 = tinyblok_now_ms();
    if (state.rule14_bt12.timeTick(now_ms)) |__c| {
        pb.emitFloat("tinyblok.heap.bar.open", __c.open, 6);
        pb.emitFloat("tinyblok.heap.bar.high", __c.high, 6);
        pb.emitFloat("tinyblok.heap.bar.low", __c.low, 6);
        pb.emitFloat("tinyblok.heap.bar.close", __c.close, 6);
    }
    if (state.rule14_bt12.nextDeadlineMs()) |__dl| {
        tinyblok_clock_arm(2, deadlineUsFromNow(__dl));
    }
}

pub const ClockSlot = extern struct {
    fire: *const fn () callconv(.c) void,
};

export const tinyblok_clock_slot_count: usize = 3;
export const tinyblok_clock_slots: [3]ClockSlot = .{
    .{ .fire = &tinyblok_clock_rule5_sa5_fire },
    .{ .fire = &tinyblok_clock_rule6_dbn6_fire },
    .{ .fire = &tinyblok_clock_rule14_bt12_fire },
};
